server:
  port: 8080

spring:
  security:
    user:
      name: admin
      password: 2527

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://kit.clqqii6k21l4.ap-northeast-2.rds.amazonaws.com:3306/cafe-flow
    username: admin
    password: dhfpswl0923
  ssh:
    remote_jump_host: 3.39.150.38
    user: ubuntu
    private_key: "C:\\workspace\\downloads\\keys\\my-ec2-keypair.pem"
    database_port: 3306

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG


app:
  jwt:
    secret: "afee9ff139300837761676667d913ed901b7d6a7119053311e1b2e63fd47a48e"
    expiration: 86400000